services:
  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polyagents-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      api:
        condition: service_healthy
    networks:
      - polyagents-network

  api:
    build: .
    container_name: polyagents-api-dev
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - QDRANT_HOST=qdrant
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - API_KEY_ENABLED=false
      - RATE_LIMITING_ENABLED=false
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    networks:
      - polyagents-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: polyagents-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    networks:
      - polyagents-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: polyagents-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=polyagents
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - polyagents-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d polyagents"]
      interval: 10s
      timeout: 5s
      retries: 3

  qdrant:
    image: qdrant/qdrant:latest
    container_name: polyagents-qdrant-dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data_dev:/qdrant/storage
    networks:
      - polyagents-network
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  redis_data_dev:
    driver: local
  postgres_data_dev:
    driver: local
  qdrant_data_dev:
    driver: local

networks:
  polyagents-network:
    driver: bridge 